# Generated by Django 5.2.17 on 2026-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WEAPON', 'Weapon'), ('VEHICLE', 'Vehicle'), ('AMMUNITION', 'Ammunition')], max_length=50)),
            ],
        ),
    ]
